title = "好好工作"
description = "让你的生活更美好"
# this filed used by manifest plugin
# which only supports:
# - project root based relative path
# - absolute path
# - remote url
# so, we must use absolute path at here
# logo = "https://github.com/jiusanzhou.png"
logo = "${__dirname}/images/wellwellwork.png"
version = "alpha"
primaryColor = "green"
baseContentDir = [ "${__dirname}/content" ]
zoePlugins = [ "src/plugins/blog-post" ]
gtagTrackingIds = [ "UA-101239170-1" ]

[author]
name = "Zoe"
email = "hi@zoe.im"
homepage = "https://zoe.im"
avatar = "https://github.com/jiusanzhou.png"
github = "jiusanzhou"
twitter = "jiusanzhou"
facebook = "jiusanzhou"
telegram = "jiusanzhou"
linkedin = "jiusanzhou"

[[navs]]
title = "关于我们"
href = "/about"

[socials]
email = "hi@wellwell.work"
github = "wellwellwork"
twitter = "wellwellwork"
facebook = "wellwellwork"
telegram = "wellwellwork"
linkedin = "wellwellwork"

[copyright]
from = 2_018
holder = "${zoe.author.name}"
location = "Hangzhou"

[layouts]
default = """
maxWidth: ${zoe.maxWidth} # ["100%", "80%", "80%", "80%", "60rem"]
header:
  logoProps:
    textColor: 'unset'
footer:
  disableBorder: true
  disableGotop: true
  disableLogo: false
  disableSocials: false
  disableLinks: false
  logoProps:
    textColor: 'unset'
"""